
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

contract Wallet_l5 {

    constructor() public {
        require(tvm.pubkey() != 0, 101);   
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

    modifier checkOwnerAndAccept {      
        require(msg.pubkey() == tvm.pubkey(), 100);
		tvm.accept();
		_;

	}
  
    function sendAllAndKill(address desti) public pure checkOwnerAndAccept { //Переслать все деньги и удалить кошелек.

        desti.transfer(10, false, 160);
    }

    function sendWithComission(address desti, uint128 value) public pure checkOwnerAndAccept { // Часть означенной суммы уйдёт на комиссию

        desti.transfer(value, true, 0);
    }  

    function sendWithoutComission(address desti, uint128 value) public pure checkOwnerAndAccept { // Комиссия будет вычтена сверху означенной суммы.

        desti.transfer(value, true, 0);
    }

}