
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

contract Giver {

    constructor() public {
        require(tvm.pubkey() != 0, 101);   
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
    }

    modifier checkOwnerAndAccept {
		tvm.accept();
		_;
	}
  
    function sendAllAndKill(address desti) public checkOwnerAndAccept { //Переслать все деньги и удалить кошелек.

        desti.transfer(10, false, 160);
    }

    function sendAndPayFees(address desti, uint128 value) public checkOwnerAndAccept { // Часть означенной суммы уйдёт на комиссию

        desti.transfer(value, false, 1);
    }  

    function send(address desti, uint128 value) public checkOwnerAndAccept { // Комиссия будет вычтена сверху означенной суммы.

        desti.transfer(value, false, 0);
    }

}